name: OnlineTimePM4
main: skyss0fly\OnlineTimePM4\Main
version: 1.0
api: 4.18.3
load: POSTWORLD
author: skyss0fly
description: Measure time spent online
website: https://github.com/skyss0fly/OnlineTimePM4

commands:
 onlinetime:
  aliases: [ot, otime]
  description: "View how much time you've spent on the server"
  permission: onlinetime

permissions:
 reset.onlinetime:
  default: op
  description: "reset"
 onlinetime:
  default: true
  description: "ot"
